export default defineEventHandler(() => {
  return [
    {
      id: '5',
      modelo: 'Chevrolet Onix Plus LT',
      brand: 'Chevrolet',
      variacao: '-4.5%',
      preco: 68000,
      imagem: '/imgs/search-example.jpg',
      year: 2021,
      km: 45000,
      horsepower: 116,
      uf: 'SP',
    },
    {
      id: '6',
      modelo: 'Nissan Versa Sense',
      brand: 'Nissan',
      variacao: '-3.8%',
      preco: 72000,
      imagem: '/imgs/search-example.jpg',
      year: 2020,
      km: 50000,
      horsepower: 118,
      uf: 'RJ',
    },
    {
      id: '7',
      modelo: 'Renault Logan Zen',
      brand: 'Renault',
      variacao: '-3.2%',
      preco: 62000,
      imagem: '/imgs/search-example.jpg',
      year: 2021,
      km: 38000,
      horsepower: 82,
      uf: 'MG',
    },
    {
      id: '8',
      modelo: 'Ford Ka Sedan SE',
      brand: 'Ford',
      variacao: '-2.9%',
      preco: 58000,
      imagem: '/imgs/search-example.jpg',
      year: 2020,
      km: 42000,
      horsepower: 88,
      uf: 'PR',
    },
  ]
})
