export default defineEventHandler(() => {
  return [
    {
      id: '1',
      modelo: 'BMW M235i Gran Coupé',
      brand: 'BMW',
      variacao: '+3.2%',
      preco: 249000,
      imagem: '/imgs/search-example.jpg',
      year: 2023,
      km: 15000,
      horsepower: 306,
      uf: 'SP',
    },
    {
      id: '2',
      modelo: 'Audi RS3 Sportback',
      brand: 'Audi',
      variacao: '+2.8%',
      preco: 485000,
      imagem: '/imgs/search-example.jpg',
      year: 2023,
      km: 8000,
      horsepower: 400,
      uf: 'RJ',
    },
    {
      id: '3',
      modelo: 'Porsche 911 Carrera S',
      brand: 'Porsche',
      variacao: '+2.5%',
      preco: 850000,
      imagem: '/imgs/search-example.jpg',
      year: 2022,
      km: 12000,
      horsepower: 450,
      uf: 'SP',
    },
    {
      id: '4',
      modelo: 'Volkswagen Golf GTI',
      brand: 'Volkswagen',
      variacao: '+2.1%',
      preco: 175000,
      imagem: '/imgs/search-example.jpg',
      year: 2023,
      km: 5000,
      horsepower: 230,
      uf: 'MG',
    },
  ]
})
